// RewindOS update-check proxy + public usage-transparency page.
//
// Two signals feed one counter: the app's update check (also edge-cached to
// shield GitHub's rate limit) and the daemon's /beat heartbeat. CheckCounter
// counts distinct devices per day by hashing the caller IP with a per-day
// input + a server-only salt — same device/day dedupes, different days can't
// be linked. No IP is stored; a day's hashes are dropped once it rolls over,
// leaving only (day, devices, checks). Observability is off; /stats shows all.

import { DurableObject } from "cloudflare:workers";

const REPO = "jaypopat/rewindos";
const UPSTREAM = `https://api.github.com/repos/${REPO}/releases/latest`;
const CACHE_TTL_SECONDS = 300;

// Env (the COUNTER binding) is generated by `wrangler types`; never hand-written.
// Index signature so these satisfy SqlStorage's row constraint (exec<T> needs it).
interface DayRow {
  day: string;
  version: string;
  platform: string;
  devices: number;
  checks: number;
  [k: string]: SqlStorageValue;
}

// Normalize client-supplied dimensions: bound cardinality and reject junk so a
// hostile client can't spam the table with garbage rows.
function normVersion(v: string | null): string {
  return v && /^\d+\.\d+\.\d+$/.test(v) ? v : "unknown";
}
const PLATFORMS = ["kde", "gnome", "hyprland", "sway", "cosmic", "xfce"];
function normPlatform(p: string | null): string {
  const s = (p ?? "").toLowerCase();
  if (s.includes("plasma")) return "kde";
  return PLATFORMS.find((k) => s.includes(k)) ?? "other";
}

interface MetaRow {
  v: string;
  [k: string]: SqlStorageValue;
}

export class CheckCounter extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    const sql = this.ctx.storage.sql;
    sql.exec(
      "CREATE TABLE IF NOT EXISTS daily (day TEXT, version TEXT, platform TEXT, checks INTEGER NOT NULL DEFAULT 0, devices INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, version, platform))",
    );
    sql.exec(
      "CREATE TABLE IF NOT EXISTS seen (day TEXT, version TEXT, platform TEXT, h TEXT, PRIMARY KEY (day, version, platform, h))",
    );
    sql.exec("CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT NOT NULL)");
  }

  // Stable random salt; with the per-day input it makes hashes irreversible
  // (salt never leaves the DO) and un-linkable across days.
  private salt(): string {
    const sql = this.ctx.storage.sql;
    const read = () => sql.exec<MetaRow>("SELECT v FROM meta WHERE k = 'salt'").toArray()[0]?.v;
    const existing = read();
    if (existing) return existing;
    const bytes = crypto.getRandomValues(new Uint8Array(32));
    const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
    // OR IGNORE + re-read: if a concurrent first-ever call won the insert, take
    // its salt, not ours — both requests must hash with the same one.
    sql.exec("INSERT OR IGNORE INTO meta (k, v) VALUES ('salt', ?)", hex);
    return read() ?? hex;
  }

  private async fingerprint(day: string, ip: string): Promise<string> {
    const data = new TextEncoder().encode(`${this.salt()}|${day}|${ip}`);
    const digest = await crypto.subtle.digest("SHA-256", data);
    return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
  }

  async record(day: string, ip: string, version: string, platform: string): Promise<void> {
    const h = await this.fingerprint(day, ip);
    const sql = this.ctx.storage.sql;
    // Load-bearing: no `await` from here down. The DO is single-threaded, so
    // the seen-insert + daily upsert run as one uninterrupted unit; an await
    // would let a concurrent record() interleave and corrupt the count.
    const inserted =
      sql.exec(
        "INSERT OR IGNORE INTO seen (day, version, platform, h) VALUES (?, ?, ?, ?)",
        day,
        version,
        platform,
        h,
      ).rowsWritten > 0;
    sql.exec(
      "INSERT INTO daily (day, version, platform, checks, devices) VALUES (?, ?, ?, 1, ?) " +
        "ON CONFLICT(day, version, platform) DO UPDATE SET checks = checks + 1, devices = devices + ?",
      day,
      version,
      platform,
      inserted ? 1 : 0,
      inserted ? 1 : 0,
    );
    // Drop earlier days' hashes (dedup-only). Runs on the first hit of a new
    // day, not at midnight — closed-day hashes linger till then, never read.
    sql.exec("DELETE FROM seen WHERE day < ?", day);
  }

  // Full history, one row per (day, version, platform). Daily rows are tiny and
  // never pruned, so dashboards get the whole timeline.
  all(): DayRow[] {
    return this.ctx.storage.sql
      .exec<DayRow>("SELECT day, version, platform, devices, checks FROM daily ORDER BY day, version, platform")
      .toArray();
  }
}

function json(body: unknown, status = 200, extra: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...extra },
  });
}

// X-Debug-IP lets tests fake distinct devices, honored only at a localhost
// host (wrangler dev). The deployed worker is never addressable at localhost,
// so it's unreachable in prod — no spoofing the device identity.
function clientIp(request: Request): string {
  const edge = request.headers.get("CF-Connecting-IP");
  const host = new URL(request.url).hostname;
  if (host === "localhost" || host === "127.0.0.1") {
    return request.headers.get("X-Debug-IP") ?? edge ?? "0.0.0.0";
  }
  return edge ?? "0.0.0.0";
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return json({ error: "method not allowed" }, 405, { Allow: "GET, HEAD" });
    }

    const { pathname } = new URL(request.url);
    const counter = env.COUNTER.getByName("prod");
    const today = new Date().toISOString().slice(0, 10);
    const hit = () =>
      counter.record(
        today,
        clientIp(request),
        normVersion(request.headers.get("X-RewindOS-Version")),
        normPlatform(request.headers.get("X-RewindOS-Platform")),
      );

    if (pathname === "/" || pathname === "/stats") {
      // Method-led, no live figures: the page proves WHAT is collected; the
      // actual counts live in /stats.json for anyone who wants to verify.
      return new Response(statsPage(), {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    if (pathname === "/stats.json") {
      return json({
        measures: "distinct devices per (day, version, platform). 'checks' is raw request volume.",
        method:
          "each request's IP is hashed with a daily input + server-only salt, deduped, then discarded; only the counts are kept. version + platform are client-reported install attributes, stored as aggregate counts only.",
        source: `https://github.com/${REPO}/tree/master/workers/update-proxy`,
        rows: await counter.all(),
      });
    }

    // Daemon heartbeat: count the device, return nothing else.
    if (pathname === "/beat") {
      ctx.waitUntil(hit().catch(() => {}));
      return json({ ok: true });
    }

    if (pathname !== `/repos/${REPO}/releases/latest`) {
      return json({ error: "not found" }, 404);
    }

    // Update check also counts the device (deduped with the daemon beat by IP),
    // off the response path — a counter failure must never block updates.
    ctx.waitUntil(hit().catch(() => {}));

    let upstream: Response;
    try {
      upstream = await fetch(UPSTREAM, {
        headers: {
          // GitHub's API rejects UA-less requests.
          "User-Agent": "rewindos-update-proxy",
          Accept: "application/vnd.github+json",
        },
        cf: { cacheTtl: CACHE_TTL_SECONDS, cacheEverything: true },
      });
    } catch (e) {
      return json({ error: `upstream fetch failed: ${e}` }, 502);
    }

    if (!upstream.ok) {
      // 503 on rate-limit so clients treat it as transient; the desktop app
      // falls back to api.github.com directly on any proxy failure.
      return json(
        { error: `github responded ${upstream.status}` },
        upstream.status === 403 || upstream.status === 429 ? 503 : 502,
      );
    }

    return new Response(upstream.body, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": `public, max-age=${CACHE_TTL_SECONDS}`,
      },
    });
  },
};

// Quiet Editorial (src/index.css): warm near-black, one terracotta ink,
// Newsreader display, mono micro-labels, hairlines not boxes. Method-led — it
// proves WHAT is collected; the live counts are in /stats.json, not here.
function statsPage(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RewindOS · Data transparency</title>
<meta name="description" content="Exactly what RewindOS collects, how, and why — a daily anonymous count, nothing more.">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect width='16' height='16' rx='3' fill='%230e0d0b'/%3E%3Ccircle cx='8' cy='8' r='3.5' fill='%23e8825a'/%3E%3C/svg%3E">
<!-- Bunny Fonts: zero-log CDN — a tracking font CDN on a privacy page would be absurd -->
<link rel="preconnect" href="https://fonts.bunny.net">
<link rel="stylesheet" href="https://fonts.bunny.net/css?family=newsreader:400,400i,500|inter:400,500|jetbrains-mono:400&display=swap">
<style>
  :root {
    --surface: #0e0d0b; --raised: #131210;
    --line: #211f1b; --line-2: #2c2925; --line-hi: #3a352d;
    --accent: #e8825a; --accent-hi: #f0986f;
    --accent-muted: rgba(232,130,90,.12); --accent-line: rgba(232,130,90,.3);
    --ink: #ece7dd; --ink-2: #a39c8d; --muted: #7d7668; --faint: #564f42;
    --sage: #9aa873;
    --display: "Newsreader", Georgia, serif;
    --sans: "Inter", system-ui, sans-serif;
    --mono: "JetBrains Mono", ui-monospace, monospace;
    --ease-quiet: cubic-bezier(.22,.61,.36,1);
    color-scheme: dark;
  }
  * { box-sizing: border-box; margin: 0; }
  ::selection { background: var(--accent-muted); color: var(--ink); }
  body {
    font: 400 15px/1.6 var(--sans);
    letter-spacing: -.005em;
    background: var(--surface); color: var(--ink);
    -webkit-font-smoothing: antialiased;
    max-width: 41rem; margin: 0 auto;
    padding: clamp(3rem, 10vh, 6rem) 1.5rem 4rem;
  }
  .kicker {
    font: 400 11px/1 var(--mono);
    letter-spacing: .18em; text-transform: uppercase; color: var(--muted);
    display: flex; align-items: center; gap: .6em;
  }
  .dot {
    width: 6px; height: 6px; border-radius: 99px; background: var(--sage);
    animation: led 2.4s ease-out infinite;
  }
  @keyframes led {
    0% { box-shadow: 0 0 0 0 rgba(154,168,115,.4); }
    70% { box-shadow: 0 0 0 6px rgba(154,168,115,0); }
    100% { box-shadow: 0 0 0 0 rgba(154,168,115,0); }
  }
  h1 {
    font: 500 clamp(1.9rem, 5vw, 2.6rem)/1.15 var(--display);
    letter-spacing: -.02em; margin: 1.1rem 0 .9rem;
  }
  h1 em { font-style: italic; font-weight: 400; color: var(--accent-hi); }
  .lede { color: var(--ink-2); max-width: 36rem; }
  .lede a { color: inherit; }

  section { margin-top: 3.2rem; padding-top: 1.4rem; border-top: 1px solid var(--line); }
  section .kicker { margin-bottom: 1.1rem; }
  p { max-width: 36rem; color: var(--ink-2); }
  p + p { margin-top: .7rem; }
  b { color: var(--ink); font-weight: 500; }

  /* The whole dataset, as a schema — the proof is the shape, not any number. */
  .code {
    font: 400 13px/1.7 var(--mono);
    background: var(--raised); border: 1px solid var(--line-2); border-radius: 8px;
    padding: 1.1rem 1.3rem; margin-bottom: 1.1rem; overflow-x: auto;
    color: var(--ink); white-space: pre;
  }
  .code .c { color: var(--faint); }
  .code .k { color: var(--accent-hi); }

  .list { list-style: none; }
  .list li {
    padding: .7rem 0; border-top: 1px solid var(--line);
    color: var(--ink-2); display: flex; gap: .8rem;
  }
  .list li:first-child { border-top: 0; }
  .list b { flex: 0 0 8.5rem; color: var(--ink); }
  code { font-family: var(--mono); font-size: .88em; color: var(--accent-hi); }

  p a, footer a, .list a {
    color: var(--accent-hi); text-decoration: underline;
    text-decoration-color: var(--accent-line); text-underline-offset: 3px;
  }
  p a:hover, footer a:hover { text-decoration-color: var(--accent-hi); }

  footer {
    margin-top: 3.2rem; padding-top: 1.4rem; border-top: 1px solid var(--line);
    display: flex; justify-content: space-between; gap: 1rem;
    font: 400 11px/1 var(--mono); letter-spacing: .08em; color: var(--faint);
  }
  footer a { color: var(--muted); text-decoration: none; }
  footer a:hover { color: var(--ink-2); }

  .reveal { animation: up .6s var(--ease-quiet) backwards; }
  .reveal:nth-of-type(2) { animation-delay: .08s; }
  .reveal:nth-of-type(3) { animation-delay: .16s; }
  .reveal:nth-of-type(4) { animation-delay: .24s; }
  .reveal:nth-of-type(5) { animation-delay: .32s; }
  @keyframes up { from { opacity: 0; transform: translateY(10px); } }
  @media (prefers-reduced-motion: reduce) {
    .reveal, .dot { animation: none !important; }
  }
</style>
</head>
<body>
  <header class="reveal">
    <div class="kicker"><span class="dot"></span>RewindOS · Data transparency</div>
    <h1>Everything this project collects <em>fits in one table.</em></h1>
    <p class="lede">RewindOS is local-only — your screen history never leaves your
    machine. It reaches the network for one thing: a daily check-in (the app's
    update check and the capture daemon's heartbeat). Here is exactly what that
    records, in full.</p>
  </header>

  <section class="reveal">
    <div class="kicker">What we store</div>
    <div class="code"><span class="k">CREATE TABLE</span> daily (
  day      <span class="k">TEXT</span>     <span class="c">-- "2026-06-13"</span>
  version  <span class="k">TEXT</span>     <span class="c">-- app version, e.g. "1.0.11"</span>
  platform <span class="k">TEXT</span>     <span class="c">-- desktop: kde / gnome / hyprland / sway / other</span>
  devices  <span class="k">INTEGER</span>  <span class="c">-- distinct devices in that bucket</span>
  checks   <span class="k">INTEGER</span>  <span class="c">-- total check-ins in that bucket</span>
)</div>
    <p>One row per day per version per desktop — counts only. Version and
    desktop are install attributes (which release is live, KDE vs GNOME), kept
    as aggregates, never tied to you. No IP, no identifier, no account, no
    payload, no per-event log — there is no other table. The live contents are
    at <a href="/stats.json">/stats.json</a>.</p>
  </section>

  <section class="reveal">
    <div class="kicker">How a device is counted</div>
    <p>On each check-in the worker hashes your IP together with the date and a
    random, server-only salt, uses that hash to dedupe within the day, then
    <b>discards it</b> — a day's hashes are dropped once the next day's first
    request arrives, leaving only the counts above. The salt never leaves the
    server, and because the date is part of the hash, a device can't be linked
    from one day to the next.</p>
    <p>Counting is by IP, so <b>devices is approximate</b>: a shared network
    merges several into one, a dual-stack connection can split one into two.
    It's a rough floor, not a precise headcount.</p>
  </section>

  <section class="reveal">
    <div class="kicker">What we never do</div>
    <ul class="list">
      <li><b>No IPs stored</b> hashed for same-day dedup, then discarded.</li>
      <li><b>No logging</b> request observability is turned off on the worker.</li>
      <li><b>No linking</b> the daily salt makes cross-day tracking impossible.</li>
      <li><b>No third parties</b> one Cloudflare Worker, open source, in this repo.</li>
      <li><b>Opt out</b> set <code>usage_heartbeat = false</code> under <code>[privacy]</code> to send nothing.</li>
    </ul>
  </section>

  <section class="reveal">
    <div class="kicker">Verify it</div>
    <p>This page is served by the same worker the app checks in to —
    <a href="https://github.com/${REPO}/tree/master/workers/update-proxy">read its source</a>,
    or take the raw counts from <a href="/stats.json">/stats.json</a>.
    The desktop app is open source too: every request it makes is in
    <a href="https://github.com/${REPO}/blob/master/src-tauri/src/updater.rs">updater.rs</a>.</p>
  </section>

  <footer>
    <a href="https://github.com/${REPO}">github.com/${REPO}</a>
    <span>one table · anonymous aggregates</span>
  </footer>
</body>
</html>`;
}
