pub mod app_label;
pub mod chat;
pub mod chat_store;
pub mod config;
pub mod db;
pub mod embedding;
pub mod error;
pub mod hasher;
pub mod mcp;
pub mod ocr;
pub mod paddle_ocr;
pub mod schema;
pub mod summary;
pub mod usage;
pub mod vault;
pub mod whisper_model;

pub use config::AppConfig;
pub use db::Database;
pub use error::{CoreError, Result};
